name: shed
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  aria2cf:
    path: ../aria2cf
    # git:
    #   url: https://github.com/DrkXo/aria2cf
    #   ref: master
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.8
  logger: ^2.4.0
  connectivity_plus: ^6.0.5
  connectivity_plus_platform_interface: ^2.0.1
  shared_preferences: ^2.3.2
  animations: ^2.0.11
  google_fonts: ^6.2.1
  collection: ^1.18.0
  form_builder_validators: ^11.0.0
  modal_bottom_sheet: ^3.0.0
  equatable: ^2.0.5
  window_manager: ^0.4.2
  system_theme: ^3.1.2
  bitsdojo_window: ^0.1.6
  rxdart: ^0.28.0
  envied: ^0.5.4+1
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  bot_toast: ^4.1.3
  tray_manager: ^0.2.4
  process: ^5.0.2
  dynamic_color: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  envied_generator: ^0.5.4+1


flutter:
  uses-material-design: true
  assets:
    - assets/aria2c/android/x64/
    - assets/aria2c/linux/x64/
    - assets/aria2c/macos/
    - assets/aria2c/windows/x64/
    - assets/aria2c/config/
    - assets/logo/shed.png
